openapi: 3.0.3
info:
  title: Todo Full-Stack Web Application API
  description: RESTful API for the secure, multi-user todo application with authentication and data isolation
  version: 1.0.0
  contact:
    name: Todo Application Support
    email: support@todoapp.example.com

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.example.com
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - id
        - email
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
        email:
          type: string
          format: email
          description: User's email address
        created_at:
          type: string
          format: date-time
          description: Timestamp when user account was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when user account was last updated
        is_active:
          type: boolean
          description: Whether the account is active
          default: true

    Todo:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the todo
        title:
          type: string
          maxLength: 500
          description: Title of the todo item (from spec clarifications)
        description:
          type: string
          nullable: true
          description: Optional detailed description of the todo
        completed:
          type: boolean
          description: Whether the todo is completed
          default: false
        user_id:
          type: string
          format: uuid
          description: Foreign key linking to the owning user
        created_at:
          type: string
          format: date-time
          description: Timestamp when todo was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when todo was last updated

    TodoCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 500
          description: Title of the todo item (from spec clarifications)
        description:
          type: string
          nullable: true
          description: Optional detailed description of the todo

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 500
          description: Title of the todo item (from spec clarifications)
        description:
          type: string
          nullable: true
          description: Optional detailed description of the todo
        completed:
          type: boolean
          description: Whether the todo is completed

    TodoToggle:
      type: object
      required:
        - completed
      properties:
        completed:
          type: boolean
          description: New completion status for the todo

    AuthRegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          minLength: 8
          description: User's password (from spec clarifications: 8+ chars, mixed case, number, special char)

    AuthLoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password

    AuthResponse:
      type: object
      required:
        - access_token
        - token_type
      properties:
        access_token:
          type: string
          description: JWT access token
        token_type:
          type: string
          description: Type of token (usually "bearer")

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message

  responses:
    UnauthorizedError:
      description: Authentication required or invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFoundError:
      description: Requested resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - BearerAuth: []

paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account with the provided credentials
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRegisterRequest'
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Login to existing account
      description: Authenticates user and returns JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me:
    get:
      summary: Get current user info
      description: Returns information about the currently authenticated user
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /todos/:
    get:
      summary: Get all todos for current user
      description: Returns a list of all todos belonging to the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of todos for the current user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Create a new todo
      description: Creates a new todo item for the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '200':
          description: Todo successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /todos/{todo_id}:
    get:
      summary: Get a specific todo
      description: Returns details of a specific todo item if it belongs to the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to retrieve
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    put:
      summary: Update a specific todo
      description: Updates details of a specific todo item if it belongs to the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a specific todo
      description: Deletes a specific todo item if it belongs to the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to delete
      responses:
        '204':
          description: Todo successfully deleted
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /todos/{todo_id}/toggle:
    patch:
      summary: Toggle todo completion status
      description: Toggles the completion status of a specific todo item if it belongs to the authenticated user
      tags:
        - Todos
      security:
        - BearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the todo to toggle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoToggle'
      responses:
        '200':
          description: Todo completion status successfully toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'